export const CREATION_SHOW_DESCR = 'CREATION_SHOW_DESCR';
export const STAT_PLUS = 'STAT_PLUS';
export const STAT_INCREMENT = 'STAT_INCREMENT';
export const STAT_MINUS = 'STAT_MINUS';
export const STAT_DECREMENT = 'STAT_DECREMENT';