export const CREATION_SHOW_DESCR = 'CREATION_SHOW_DESCR';
export const STAT_PLUS = 'STAT_PLUS';
export const STAT_INCREMENT = 'STAT_INCREMENT';
export const STAT_MINUS = 'STAT_MINUS';
export const STAT_DECREMENT = 'STAT_DECREMENT';
export const CHANGE_ORIGIN = 'CHANGE_ORIGIN';
export const CHANGE_NAME = 'CHANGE_NAME';
export const LOAD_CHARACTER = 'LOAD_CHARACTER';